### ISSUE TITLE
Unable to pull city data

### ISSUE THREAD

**Issue by brandonneal** [rainbow-sh/Wfetch#1]
I am unable to pull my city data however, OWM does see my city on their site.
I get a "Place not found" error.

My city: Lake City, FL
Listed [here](https://openweathermap.org/city/4161187) as Lake City, US
I'm defaulted to Jacksonville when I run without --place

Perhaps allow for selecting location based on location ID, which in my case would be the 4161187 part of the URL.

**Comment by Gcat101** [comment]
Please go to https://ipinfo.io/ and send your ip address region data

**Comment by brandonneal** [comment]
Sharing my city is one thing but, I'm not too comfortable giving out my IP. I hope you understand.

**Comment by Gcat101** [comment]
No, I'm just asking for the city and the county.

**Comment by brandonneal** [comment]
Ahh, I misread that

 city: "Jacksonville"
 region: "Florida"
 country: "US"

I know this is why wfetch defaults to Jacksonville, that's why I was trying to do 

wfetch --place="Lake City, US"
and was getting
PLACE NOT FOUND.

**Comment by Gcat101** [comment]
Fixed + added id support. Update wfetch
