### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by nicc777** [rainbow-sh/Wfetch#4]
Followed the instructions and got it to work after I manually copied the `icons/` directory to `/usr/local/bin` which is not recommended, obviously.

I don't have time right now to figure this out, but I guess you also need to copy the icons directory somewhere sane and then look for it there first.

Otherwise, great work!

Running on Ubuntu (Kubuntu) 20.04.3 LTS.

**Comment by Gcat101** [comment]
Ok, i know what happened

**Comment by Gcat101** [comment]
Fixed. Update wfetch by running the same command
