### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by brandonneal** [rainbow-sh/Wfetch#8]
nodnarb@Odyssey:~/Downloads/Wfetch$ sudo ./install.sh
Installing package requirements...
Installing package...
Cleaning up...
Package Installed!

Please add this line to your shell profile (You are using /bin/bash):
'export WEATHER_CLI_API=<your OWM api key>'

nodnarb@Odyssey:~/Downloads/Wfetch$ wfetch
Traceback (most recent call last):
  File "/usr/local/bin/wfetch", line 81, in main
    try: ICON = open(os.path.join(ICONPATH, 'neutral', f'{STATUS}.txt')).read().splitlines() # Get neutral icon from /icons/neutral directory
FileNotFoundError: [Errno 2] No such file or directory: '/home/nodnarb/.wfetch/icons/neutral/clear_sky.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wfetch", line 83, in main
    try: ICON = open(os.path.join(ICONPATH, ASCIITYPE, f'{STATUS}.txt')).read().splitlines() # Get icon from /icons/(day|night) directory
FileNotFoundError: [Errno 2] No such file or directory: '/home/nodnarb/.wfetch/icons/night/clear_sky.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wfetch", line 125, in <module>
    Fire(main) # Launch main function with arguments
  File "/home/nodnarb/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/nodnarb/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/nodnarb/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/bin/wfetch", line 84, in main
    except FileNotFoundError: ICON = open(os.path.join(ICONPATH, 'unknown.txt')).read().splitlines() # If not found, display "?"
FileNotFoundError: [Errno 2] No such file or directory: '/home/nodnarb/.wfetch/icons/unknown.txt'
nodnarb@Odyssey:~/Downloads/Wfetch$

I got an error after initially trying to update and thought I fat fingered it so, I removed all traces of wfetch from my system git cloned again and ran the install script now I'm getting this error. Also before I could run it I had to fix line 1 in install.sh because it read "#!bin/bash" instead of "#!/bin/bash"

**Comment by Gcat101** [comment]
Do you have a ./wfetch directory in your home folder?

**Comment by Gcat101** [comment]
nvm i fixed it
